import { http } from './http'
export const api={
  login:(username:string,password:string)=>http.post('/auth/login',{username,password}),
  dashboard:()=>http.get('/dashboard/summary'),dashboardAnalytics:()=>http.get('/dashboard/analytics'),
  activities:(params={})=>http.get('/activities',{params}),activity:(id:number,params={})=>http.get(`/activities/${id}`,{params}),activityImage:(activityId:number,imageId:number)=>http.get(`/activities/${activityId}/images/${imageId}`,{responseType:'blob'}),updateActivity:(id:number,data:object)=>http.put(`/activities/${id}`,data),deleteActivity:(id:number)=>http.delete(`/activities/${id}`),deleteActivities:(ids:number[])=>http.delete('/activities/batch',{data:{ids}}),
  notes:(params:{city?:string;review_status?:string;start_date?:string;end_date?:string;keyword?:string;keyword_group_ids?:number[];blogger_id?:number;blogger_group_ids?:number[];page?:number;page_size?:number}={})=>http.get('/notes',{params}),note:(id:number)=>http.get(`/notes/${id}`),noteImage:(noteId:number,imageId:number)=>http.get(`/notes/${noteId}/images/${imageId}`,{responseType:'blob'}),updateNote:(id:number,data:object)=>http.put(`/notes/${id}`,data),reviewNote:(id:number,status:'APPROVED'|'REJECTED')=>http.post(`/notes/${id}/review`,{status}),deleteNotes:(ids:number[])=>http.delete('/notes/batch',{data:{ids}}),approveNotes:(ids:number[])=>http.post('/notes/batch/approve',{ids}),reExtractNote:(id:number)=>http.post(`/notes/${id}/re-extract`),createNoteActivity:(id:number,data:object)=>http.post(`/notes/${id}/activities`,data),
  tasks:()=>http.get('/tasks'),createTask:(data:object)=>http.post('/tasks/crawl',data),restartTask:(id:number)=>http.post(`/tasks/${id}/restart`),stopTask:(id:number)=>http.post(`/tasks/${id}/stop`),logs:(id:number)=>http.get(`/tasks/${id}/logs`),batchDeleteTasks:(ids:number[])=>http.delete('/tasks/batch',{data:{ids}}),
  duplicates:()=>http.get('/duplicates'),merge:(id:number,keep='a')=>http.post(`/duplicates/${id}/merge`,{keep}),ignore:(id:number)=>http.post(`/duplicates/${id}/ignore`),
  reports:()=>http.get('/reports'),generateReport:(data:object)=>http.post('/reports/generate',data),report:(id:number)=>http.get(`/reports/${id}`),downloadReport:(id:number,format:'md'|'xlsx')=>http.get(`/reports/${id}/download`,{params:{format},responseType:'blob'}),deleteReport:(id:number)=>http.delete(`/reports/${id}`),
  settings:(kind:string)=>http.get(`/settings/${kind}`),createSetting:(kind:string,data:object)=>http.post(`/settings/${kind}`,data),updateSetting:(kind:string,id:number,data:object)=>http.put(`/settings/${kind}/${id}`,data),deleteSetting:(kind:string,id:number)=>http.delete(`/settings/${kind}/${id}`),enrichBlogger:(id:number)=>http.post(`/settings/bloggers/${id}/enrich`),downloadBloggerTemplate:()=>http.get('/settings/bloggers/import-template',{responseType:'blob'}),importBloggers:(file:File)=>http.post('/settings/bloggers/import',file,{params:{filename:file.name},headers:{'Content-Type':'application/octet-stream'}}),testOpenCLI:()=>http.post('/settings/opencli/test',undefined,{skipAuthRedirect:true} as any),openXhsLogin:()=>http.post('/settings/opencli/open-login'),batchDeleteCities:(ids:number[])=>http.post('/settings/cities/batch-delete',{ids}),batchDeleteBloggers:(ids:number[])=>http.post('/settings/bloggers/batch-delete',{ids}),
  diagnosticsSnapshot:()=>http.get('/diagnostics/snapshot'),diagnosticsOpencli:()=>http.get('/diagnostics/opencli'),diagnosticsXhsLogin:()=>http.get('/diagnostics/xhs-login'),diagnosticsXhsPool:()=>http.get('/diagnostics/xhs-pool'),
  keywordGroups:(params={})=>http.get('/settings/keyword-groups',{params}),keywordGroup:(id:number)=>http.get(`/settings/keyword-groups/${id}`),createKeywordGroup:(data:object)=>http.post('/settings/keyword-groups',data),patchKeywordGroup:(id:number,data:object)=>http.patch(`/settings/keyword-groups/${id}`,data),updateKeywordGroupWords:(id:number,words:string[])=>http.put(`/settings/keyword-groups/${id}/words`,{words}),updateKeywordGroupCities:(id:number,cityCodes:string[])=>http.put(`/settings/keyword-groups/${id}/cities`,{city_codes:cityCodes}),deleteKeywordGroup:(id:number)=>http.delete(`/settings/keyword-groups/${id}`),batchDeleteKeywordGroups:(ids:number[])=>http.post('/settings/keyword-groups/batch-delete',{ids}),
  bloggerGroups:()=>http.get('/settings/blogger-groups'),bloggerGroup:(id:number)=>http.get(`/settings/blogger-groups/${id}`),createBloggerGroup:(data:object)=>http.post('/settings/blogger-groups',data),updateBloggerGroupMembers:(id:number,bloggerIds:number[])=>http.put(`/settings/blogger-groups/${id}/members`,{blogger_ids:bloggerIds}),deleteBloggerGroup:(id:number)=>http.delete(`/settings/blogger-groups/${id}`),batchDeleteBloggerGroups:(ids:number[])=>http.post('/settings/blogger-groups/batch-delete',{ids}),
  systemConfig:()=>http.get('/settings/system-config'),updateSystemConfig:(data:object)=>http.put('/settings/system-config',data),
  xhsAccounts:()=>http.get('/xhs-accounts'),createXhsAccount:(data:object)=>http.post('/xhs-accounts',data),updateXhsAccount:(id:number,data:object)=>http.put(`/xhs-accounts/${id}`,data),deleteXhsAccount:(id:number)=>http.delete(`/xhs-accounts/${id}`),checkXhsAccountLogin:(id:number)=>http.post(`/xhs-accounts/${id}/check-login`),openXhsAccountLogin:(id:number)=>http.post(`/xhs-accounts/${id}/open-login`),batchDeleteXhsAccounts:(ids:number[])=>http.post('/xhs-accounts/batch-delete',{ids}),
  posterTemplates:()=>http.get('/settings/poster-templates'),posterTemplate:(id:number)=>http.get(`/settings/poster-templates/${id}`),createPosterTemplate:(data:object)=>http.post('/settings/poster-templates',data),updatePosterTemplate:(id:number,data:object)=>http.put(`/settings/poster-templates/${id}`,data),deletePosterTemplate:(id:number)=>http.delete(`/settings/poster-templates/${id}`),parsePosterFromImage:(file:File)=>http.post('/settings/poster-templates/parse-from-image',file,{params:{filename:file.name, name:''},headers:{'Content-Type':'application/octet-stream'}}),
  posterTasks:()=>http.get('/poster-tasks'),posterTask:(id:number)=>http.get(`/poster-tasks/${id}`),createPosterTask:(data:object)=>http.post('/poster-tasks',data),updatePosterTask:(id:number,data:object)=>http.put(`/poster-tasks/${id}`,data),deletePosterTask:(id:number)=>http.delete(`/poster-tasks/${id}`),posterCandidates:(params={})=>http.get('/poster-tasks/candidates',{params}),posterPreview:(id:number)=>http.get(`/poster-tasks/${id}/preview`),posterRender:(id:number)=>http.post(`/poster-tasks/${id}/render`),posterDownload:(id:number)=>http.get(`/poster-tasks/${id}/download`,{responseType:'blob'}),noteImages:(noteId:number)=>http.get(`/posters/note-images/${noteId}`),noteImageById:(imageId:number)=>http.get(`/posters/note-image-by-id/${imageId}`,{responseType:'blob'}),
  listUsers:()=>http.get('/users'),getUser:(id:number)=>http.get(`/users/${id}`),createUser:(data:object)=>http.post('/users',data),updateUser:(id:number,data:object)=>http.put(`/users/${id}`,data),deleteUser:(id:number)=>http.delete(`/users/${id}`),updateUserGroups:(id:number,group_ids:number[])=>http.put(`/users/${id}/groups`,{group_ids}),
  listGroups:()=>http.get('/groups'),createGroup:(data:object)=>http.post('/groups',data),updateGroup:(id:number,data:object)=>http.put(`/groups/${id}`,data),deleteGroup:(id:number)=>http.delete(`/groups/${id}`),updateGroupPermissions:(id:number,permission_codes:string[])=>http.put(`/groups/${id}/permissions`,{permission_codes}),
  listPermissions:()=>http.get('/permissions'),
  listAuditLogs:(params:{actor_username?:string;action?:string[];date_from?:string;date_to?:string;page?:number;size?:number}={})=>{const qs=new URLSearchParams();if(params.actor_username)qs.set('actor_username',params.actor_username);(params.action??[]).forEach(a=>qs.append('action',a));if(params.date_from)qs.set('date_from',params.date_from);if(params.date_to)qs.set('date_to',params.date_to);qs.set('page',String(params.page??1));qs.set('size',String(params.size??20));return http.get(`/audit-logs?${qs.toString()}`)},
  deleteAuditLogs:(ids:number[])=>http.delete('/audit-logs',{data:{ids}}),
  platforms:()=>http.get('/platforms'),
  platformAccounts:(params:{platform?:string}={})=>http.get('/platform-accounts',{params}),
  createPlatformAccount:(data:object)=>http.post('/platform-accounts',data),
  updatePlatformAccount:(id:number,data:object)=>http.put(`/platform-accounts/${id}`,data),
  deletePlatformAccount:(id:number)=>http.delete(`/platform-accounts/${id}`),
  checkPlatformAccountLogin:(id:number)=>http.post(`/platform-accounts/${id}/check-login`),
  nurturePlatformAccount:(id:number,data:object)=>http.post(`/platform-accounts/${id}/nurture`,data),
  favoriteSnapshots:(id:number)=>http.get(`/platform-accounts/${id}/favorites`),
  favoriteSnapshotHistory:(id:number,params={})=>http.get(`/platform-accounts/${id}/favorites/history`,{params}),
  riskConfig:()=>http.get('/risk-config'),
  saveRiskConfig:(data:object)=>http.put('/risk-config', data),
  reloadRiskConfig:()=>http.post('/risk-config/reload'),
  nurtureRunning:()=>http.get('/nurture/running'),
  nurtureHistory:(params:object)=>http.get('/nurture/history', { params }),
  nurtureTask:(id:string|number)=>http.get(`/nurture/tasks/${id}`),
  cancelNurtureTask:(id:string|number)=>http.post(`/nurture/tasks/${id}/cancel`),
  rerunNurtureTask:(id:string|number)=>http.post(`/nurture/tasks/${id}/rerun`),
  deleteNurtureTask:(id:string|number)=>http.delete(`/nurture/tasks/${id}`),
  nurtureTaskLogs:(id:string|number)=>http.get(`/nurture/tasks/${id}/logs`),
  exportNurtureHistory:(params:object)=>http.get('/nurture/export', { params, responseType:'blob' }),
  actionSets:(params:object)=>http.get('/nurture/action-sets', { params }),
  createActionSet:(data:object)=>http.post('/nurture/action-sets', data),
  updateActionSet:(id:number,data:object)=>http.patch(`/nurture/action-sets/${id}`, data),
  deleteActionSet:(id:number)=>http.delete(`/nurture/action-sets/${id}`),
  cloneActionSet:(id:number)=>http.post(`/nurture/action-sets/${id}/clone`),
  schedules:(params:object)=>http.get('/nurture/schedules', { params }),
  createSchedule:(data:object)=>http.post('/nurture/schedules', data),
  updateSchedule:(id:number,data:object)=>http.patch(`/nurture/schedules/${id}`, data),
  deleteSchedule:(id:number)=>http.delete(`/nurture/schedules/${id}`),
  enableSchedule:(id:number)=>http.post(`/nurture/schedules/${id}/enable`),
  disableSchedule:(id:number)=>http.post(`/nurture/schedules/${id}/disable`),
  triggerSchedule:(id:number)=>http.post(`/nurture/schedules/${id}/trigger`),
  notifications:(params:object)=>http.get('/notifications', { params }),
  markNotificationRead:(id:number)=>http.patch(`/notifications/${id}/read`),
  readAllNotifications:()=>http.post('/notifications/read-all'),
  notificationsUnreadCount:()=>http.get('/notifications/unread-count'),
  auditLogs:(params:object)=>http.get('/audit-logs', { params }),
  auditLog:(id:number)=>http.get(`/audit-logs/${id}`),
  exportAuditLogs:(params:object)=>http.get('/audit-logs/export', { params, responseType:'blob' }),
  operatorsMe:()=>http.get('/operators/me'),
  changePassword:(data:object)=>http.post('/operators/change-password', data),
  activityKpi:(params:object)=>http.get('/accounts/activity/kpi', { params }),
  activityHeatmap:(params:object)=>http.get('/accounts/activity/heatmap', { params }),
  activityActionCounts:(params:object)=>http.get('/accounts/activity/action-counts', { params }),
  activityPlatformCounts:(params:object)=>http.get('/accounts/activity/platform-counts', { params }),
}
